version: "3.4"
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    volumes:
      - .:/var/www/html/app
    tty: true
